# Generated by Django 4.2.11 on 2024-04-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.CharField(choices=[('N/A', 'N/A'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='N/A', max_length=3)),
                ('comment', models.TextField(max_length=300)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.destination')),
            ],
        ),
    ]
